image: brandonkrull/libpfasst
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - export BUILD_DIR=$PWD
          - cd $BUILD_DIR && make
          - cd $BUILD_DIR/tests/toda && make
          - cd $BUILD_DIR/tests/adv_diff_fft && make
          - cd $BUILD_DIR
          - nosetests
