version: 2
jobs:
    build:
        docker:
            - image: brandonkrull/libpfasst
        steps:
            - checkout
            - run:
                name: env_links
                command: cd test && ln -s ../pf && cd magpicard && ln -s ../../pf && cd ../imk && ln -s ../../pf && cd ../..
            - run: # Modify the commands below to build all the tests
                name: make_tests
                command: >
                  make  DEBUG=TRUE &&
                  cd test/magpicard &&  make &&
                  cd ../imk &&  make &&
                  cd ../nagumo && make &&
                  cd ../EXP_adv_diff_fft/1d && make &&
                  cd ../../adv_diff_fft/1d && make &&
                  cd ../2d/ && make &&
                  cd ../../.. 
            - run: # Modify the commands below to build and check all the tutorials
                name: check_tutorials
                command: >
                  cd Tutorials/EX1_Dahlquist &&  make &&
                  mpirun -n 16 ./main.exe multi_level.nml &&
                  cd ../EX2_Dahlquist &&  make DEBUG=TRUE &&
                  mpirun -n 16 ./main.exe multi_level.nml &&
                  cd ../EX3_adv_diff &&  make &&
                  mpirun -n 16 ./main.exe multi_level.nml &&
                  cd ../..
            - run: # Run the python tests in test
                name: do_pytests
                command: pytest
