version: 2
jobs:
    build:
        docker:
            - image: brandonkrull/libpfasst
        steps:
            - checkout
            - run: # Modify the commands below to build your repository.
                name: make_and_test
                command: ./test/run_tests.sh
