version: 2.1
jobs:
    build:
        docker:
            - image: libpfasst/libpfasst
        steps:
            - checkout
            - run: # Modify the commands below to build all the tests
                name: make_LibPFASST
                command: >
                  echo "Compiling Libfasst"  &&
                  cp Makefile.examples/Makefile.FFT ./  &&
                  cp Makefile.examples/Makefile.local.gnu ./Makefile.local &&
                  make  DEBUG=TRUE USE_FFT=TRUE USE_FFTW=FALSE
            - run:
                name: test env_links
                command: cd test && ln -s ../pf && cd magpicard && ln -s ../../pf && cd ../imk && ln -s ../../pf && cd ../..
            - run: # Modify the commands below to build all the tests
                name: make_tests
                command: >
                  echo "Compiling magpicard" &&		  
                  cd test/magpicard &&  make  &&
                  echo "Compiling imk"	&&	  
                  cd ../imk &&  make  &&
                  echo "Compiling nagumo"		  
                  cd ../nagumo && make  &&
                  echo "Compiling IMEX"	&&	  
                  cd ../EXP_adv_diff_fft/1d && make  &&
                  cd ../../..
            - run: # Modify the commands below to build and check all the tutorials		  
                name: check_tutorials
                command: >
                  echo "Making Tutorial 1"	&&	  		
                  cd Tutorials/EX1_Dahlquist &&  make  &&
                  echo "Making Tutorial 2"	&&	  		
                  cd ../EX2_Dahlquist &&  make DEBUG=TRUE   &&
                  echo "Making  Tutorial 3" &&	  		
                  cd ../EX3_adv_diff &&  make   &&
                  echo "Making libnpy" &&	  		
                  cd ../.. &&  make libnpy  &&
                  echo "Making Tutorial 4" &&	  		
                  cd ../EX4_Boussinesq &&  make   &&
                  echo "Done with Tutorials" &&	  		
                  cd ../..
