version: 2
jobs:
    build:
        docker:
            - image: brandonkrull/libpfasst
        steps:
            - checkout
            - run: pip install tqdm
            - run:
                name: env_links
                command: cd test && ln -s ../pf && cd toda && ln -s ../../pf && cd ../imk && ln -s ../../pf && cd ../.. && ls -lrt tests/toda
            - run: # Modify the commands below to build your repository.
                name: make_and_test
                command: OMP=y make && cd test/toda && OMP=y make  && cd ../imk && OMP=y make  && cd ../adv_diff_fft && make && cd ../.. && pytest
